/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-03 14:19:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.alibaba.fastjson.*;

public final class _60minateAnalyse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

StringBuffer moxingData = new StringBuffer("");
moxingData.append("[");
	moxingData.append("{\"id\":\"1\"");
	moxingData.append(",\"moXingName\":\"情况1\"");
	moxingData.append(",\"moXingImg\":\"\"");
	moxingData.append(",\"moXingDesc\":\"上涨阳量大于下跌阴量，我们称为良性量能，当某小时上涨阳量小于下跌阴量，同时随后出现的下跌阴量依然在放大时，显示多空力量开始转化，空方占优，同时价格跌破5单元均线，目标在技术高位死叉，为卖点。\"");
	moxingData.append(",\"moXingSuggest\":\"高位卖出.假如价格已下滑到重要均线支持位或者目标下滑到超卖区，可不必急着卖出，等候其进行技术反抽。\"");
	moxingData.append(",\"moXingOperateKeyPoint\":\"\"");
	moxingData.append(",\"moXingOperateAble\":\"1\"");
	moxingData.append(",\"moXingRelativePoint\":\"10\"");
	moxingData.append(",\"moXingStopLessRange\":\"10-20\"");
	moxingData.append(",\"moXingProfitRange\":\"10-20\"");
	moxingData.append("}");
	
	moxingData.append(",{\"id\":\"2\"");
	moxingData.append(",\"moXingName\":\"情况二\"");
	moxingData.append(",\"moXingImg\":\"\"");
	moxingData.append(",\"moXingDesc\":\"某小时下破5单元均线后，两个小时都被均线压制，无法站回均线，5单元均线向下拐头，综合指标的技术位置，为卖点。\"");
	moxingData.append(",\"moXingSuggest\":\"高位卖出.假如价格已下滑到重要均线支持位或者目标下滑到超卖区，可不必急着卖出，等候其进行技术反抽。\"");
	moxingData.append(",\"moXingOperateKeyPoint\":\"\"");
	moxingData.append(",\"moXingOperateAble\":\"1\"");
	moxingData.append(",\"moXingRelativePoint\":\"10\"");
	moxingData.append(",\"moXingStopLessRange\":\"10-20\"");
	moxingData.append(",\"moXingProfitRange\":\"10-20\"");
	moxingData.append("}");
	
	
	moxingData.append(",{\"id\":\"3\"");
	moxingData.append(",\"moXingName\":\"情况三\"");
	moxingData.append(",\"moXingImg\":\"\"");
	moxingData.append(",\"moXingDesc\":\"突然没有任何征兆的下跌，技术指标快速下滑至20以下超卖区，耐心等候其技术反抽，在指标重新反抽到技能高位时，为卖点。\"");
	moxingData.append(",\"moXingSuggest\":\"高位卖出.技术指标快速下滑至20以下超卖区，耐心等候其技术反抽，在指标重新反抽到技能高位时，为卖点\"");
	moxingData.append(",\"moXingOperateKeyPoint\":\"\"");
	moxingData.append(",\"moXingOperateAble\":\"1\"");
	moxingData.append(",\"moXingRelativePoint\":\"10\"");
	moxingData.append(",\"moXingStopLessRange\":\"10-20\"");
	moxingData.append(",\"moXingProfitRange\":\"10-20\"");
	moxingData.append("}");
	 
	
moxingData.append("]");

JSONArray jsonArrayData = JSONArray.parseArray(moxingData.toString());

      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>60 分钟线确认卖点技巧</title>\r\n");
      out.write("    <!-- 新 Bootstrap 核心 CSS 文件 -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 可选的Bootstrap主题文件（一般不用引入） -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap-theme.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->\r\n");
      out.write("\t<script src=\"http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\r\n");
      out.write("\t<script src=\"http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("     <!-- HTML5 Shim 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->\r\n");
      out.write("     <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->\r\n");
      out.write("     <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("     <![endif]-->\r\n");
      out.write("     <style type=\"text/css\">\r\n");
      out.write("     \t.hide {\r\n");
      out.write("     \t\tdisplay:none;\r\n");
      out.write("     \t}\r\n");
      out.write("     \t.show {\r\n");
      out.write("     \t\tdisplay:block;\r\n");
      out.write("     \t}\r\n");
      out.write("     </style>\r\n");
      out.write("     \r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"well\">前提条件一<br/>\r\n");
      out.write("对于常态的上涨阳线(实体阳线或实体大于上下影的阳线)和常态的下跌阴线(缩量阴线，确切的说是量能小于均量的阴线)，此为常态行情，价格在没有外力作用下，依旧会向原方向前进，我们可以安心持股。一旦某日出现剧烈震荡或者是带量下跌，在60分钟上体现为长上影，长下影，长上下影，一小时内跌幅较大的阴线，同时量能大于均量，此类K线我们称为“异动K线”。\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"well\">前提条件二<br/>\r\n");
      out.write("在经过一段时间的放量涨升后，上行能量开始减退不足，表现上攻开始乏力或者准备进入较长时间的调整，在60分钟上体现为短期均量线下破临时均量线，显示现短期量能释放的平均程度开始萎缩。\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"well\">说明<br/>\r\n");
      out.write("在出现上述两种状况的条件下，假如某日出现下面三种状况中的一种，乃至是三种状况中的任意两种复合情况(下跌几乎就成为百分百)，必须毫不犹豫，果断出局!\r\n");
      out.write("本技法只实用于短线涨升或宽幅震荡的情况，并不适用于窄幅牛皮震荡的情况和总体处于下跌趋势的情况。\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("   \t\t<li style=\"width: 200px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n");
      out.write("         <li> \r\n");
      out.write("         \t <div class=\"btn-group\" role=\"group\" aria-label=\"...\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-primary\" onclick=\"doAnalyse()\">分析结果</button>\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-success\" onclick=\"resetFn()\">重置</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("         </li>\r\n");
      out.write("      </ul> \r\n");
      out.write("</nav>\r\n");
      out.write("<table class=\"table table-condensed table-striped  table-bordered  table-hover   \">\r\n");
      out.write("\t   <caption>回答问题进行分析</caption>\r\n");
      out.write("\t   <thead>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <th style=\"width:20%\">模型</th>\r\n");
      out.write("\t         <th style=\"width:30%\">图形描述</th>\r\n");
      out.write("\t         <th style=\"width:20%\">是该状态吗?</th>\r\n");
      out.write("\t         <th style=\"width:30%\">操作建议</th>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t   </thead>\r\n");
      out.write("\t   <tbody>\r\n");
      out.write("\t   \r\n");
      out.write("\t   \t");

	   		int length = jsonArrayData.size();
	   		JSONObject json  = null;
	   		String id = null;
	   		String moXingName = null;
	   		String moXingImg = null;
	   		String moXingDesc = null;
	   		String moXingSuggest = null;
	   		String moXingOperateKeyPoint = null;
	   		String moXingOperateAble = null;
	   		String moXingRelativePoint = null;
	   		String  moXingStopLessRange = null;
	   		String moXingProfitRange = null;
	   		for (int i=0;i<length;i++){
	   			json = jsonArrayData.getJSONObject(i);
	   			id = json.getString("id");
	   			moXingName = json.getString("moXingName");
	   			moXingImg = json.getString("moXingImg");
	   			moXingDesc = json.getString("moXingDesc");
	   			moXingSuggest = json.getString("moXingSuggest");
	   			moXingOperateKeyPoint = json.getString("moXingOperateKeyPoint");
	   			moXingOperateAble = json.getString("moXingOperateAble");
	   			moXingRelativePoint =  json.getString("moXingRelativePoint");
	   			moXingStopLessRange =  json.getString("moXingStopLessRange");
	   			moXingProfitRange =   json.getString("moXingProfitRange");
	   			
      out.write("\r\n");
      out.write("\t   \t\t\t<tr id=\"tr_");
      out.print(id);
      out.write("\"><!-- class=\"info\"  active,success,warning,danger-->\r\n");
      out.write("\t\t\t         <td id=\"model_");
      out.print(id);
      out.write('"');
      out.write('>');
      out.print(moXingName);
      out.write("</td>\r\n");
      out.write("\t\t\t         <td>");
      out.print(moXingDesc);
      out.write("</td> \r\n");
      out.write("\t\t\t         <td><select id=\"sel_");
      out.print(id);
      out.write("\"><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t\t\t         <td ><span id=\"fenxi_");
      out.print(id);
      out.write("\" class=\"hide\">");
      out.print(moXingSuggest);
      out.write("</span></td>\r\n");
      out.write("\t\t\t      \r\n");
      out.write("\t\t\t      </tr>\r\n");
      out.write("\t   \t\t\t");

	   		} 
	   	
      out.write("\r\n");
      out.write("\t    </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 模态框（Modal） myModalLabel-->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <h4 class=\"modal-title\">错误</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\" id=\"alarm_content\">\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div><!-- /.modal-content -->\r\n");
      out.write("  </div><!-- /.modal-dialog -->\r\n");
      out.write("</div><!-- /.modal -->\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var asklength = \"");
      out.print(length);
      out.write("\"*1;\r\n");
      out.write("function doAnalyse(){\r\n");
      out.write("\t\tvar score = 0;\r\n");
      out.write("\t\t//先分析问题是否都回复了\r\n");
      out.write("\t\t/***/\r\n");
      out.write("\t\tvar selS = 0;\r\n");
      out.write("\t\tfor(var i=1;i<=asklength;i++){\r\n");
      out.write("\t\t\tvar v = $(\"#sel_\"+i).val();\r\n");
      out.write("\t\t\tif(v != -1){\r\n");
      out.write("\t\t\t\tselS ++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(selS == 0){\r\n");
      out.write("\t\t\t\t$(\"#alarm_content\").text(\"请选择图形状况\");\r\n");
      out.write("\t\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//将确定是的进行建议显示\r\n");
      out.write("\t\tfor(var i=1;i<=asklength;i++){\r\n");
      out.write("\t\t\tvar v = $(\"#sel_\"+i).val();\r\n");
      out.write("\t\t\tif(v != -1 && v != 0){\r\n");
      out.write("\t\t\t\t/**\r\n");
      out.write("\t\t\t\t addClass \r\n");
      out.write("\t\t\t\t */\r\n");
      out.write("\t\t\t\t $(\"#fenxi_\"+i).removeClass(\"hide\").parent().addClass(\"alert-danger\"); \r\n");
      out.write("\t\t\t\t// $(\"#operateAble_\"+i).removeClass(\"hide\").parent().addClass(\"alert-danger\"); \r\n");
      out.write("\t\t\t\t //$(\"#buypoint_\"+i).removeClass(\"hide\").parent().addClass(\"alert-danger\"); \r\n");
      out.write("\t\t\t\t //$(\"#stop_less_range_\"+i).removeClass(\"hide\").parent().addClass(\"alert-danger\"); \r\n");
      out.write("\t\t\t\t //$(\"#profit_range_\"+i).removeClass(\"hide\").parent().addClass(\"alert-danger\"); \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t //var v = $(\"#relative_point_\"+i).text();\r\n");
      out.write("\t\t\t\t// var endV = vscore*1 +v*1;\r\n");
      out.write("\t\t\t\t//$(\"#buypoint_\"+i).text(endV);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("function resetFn(){\r\n");
      out.write("\t\tfor(var i=1;i<=asklength;i++){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t $(\"#sel_\"+i).val(\"-1\");\r\n");
      out.write("\t\t\t\t $(\"#fenxi_\"+i).addClass(\"hide\").parent().removeClass(\"alert-danger\");\r\n");
      out.write("\t\t\t\t// $(\"#operateAble_\"+i).addClass(\"hide\").parent().removeClass(\"alert-danger\");\r\n");
      out.write("\t\t\t\t// $(\"#buypoint_\"+i).addClass(\"hide\").parent().removeClass(\"alert-danger\");\r\n");
      out.write("\t\t\t\t// $(\"#stop_less_range_\"+i).addClass(\"hide\").parent().removeClass(\"alert-danger\");\r\n");
      out.write("\t\t\t\t//$(\"#profit_range_\"+i).addClass(\"hide\").parent().removeClass(\"alert-danger\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
