/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-01 07:50:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dayRiskAnalyse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>日分析行情</title>\r\n");
      out.write("    <!-- 包含头部信息用于适应不同设备 -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write(" \r\n");
      out.write("     <!-- 新 Bootstrap 核心 CSS 文件 -->\r\n");
      out.write("\t<link href=\"http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 可选的Bootstrap主题文件（一般不使用） -->\r\n");
      out.write("\t<script src=\"http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap-theme.min.css\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->\r\n");
      out.write("\t<script src=\"http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\r\n");
      out.write("\t<script src=\"http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("     <!-- HTML5 Shim 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->\r\n");
      out.write("     <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->\r\n");
      out.write("     <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("     <![endif]-->\r\n");
      out.write("     \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("     <table class=\"table table-condensed table-striped  table-bordered  table-hover table-responsive  \">\r\n");
      out.write("\t   <caption>卖出分析</caption>\r\n");
      out.write("\t   <thead>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <th>模型</th>\r\n");
      out.write("\t         <th>前置操作</th>\r\n");
      out.write("\t         <th>问题</th>\r\n");
      out.write("\t         <th>回答</th>\r\n");
      out.write("\t         <th>结论</th>\r\n");
      out.write("\t         <th>结论分析</th>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t   </thead>\r\n");
      out.write("\t   <tbody>\r\n");
      out.write("\t      <tr ><!-- class=\"info\"  active,success,warning,danger-->\r\n");
      out.write("\t         <td>十字线</td>\r\n");
      out.write("\t         <td>在高价圈出现十字线（开盘收盘等价线），并留下上下影 线</td>\r\n");
      out.write("\t         <td>上影线较长?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t         <td class=\"warning\">适合做空单或卖出</td>\r\n");
      out.write("\t         <td>此情形表示白银价格经过一段时日 后，已涨得相当高，欲振乏力，开始要走下坡，这是明显 的卖出信号</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <td>覆盖线</td>\r\n");
      out.write("\t         <td>行情连续数天扬升之后，隔日以高盘开出，随后买盘不 愿追高，大势持续滑落，收盘价跌至前一日阳线之内</td>\r\n");
      out.write("\t         <td>是否这种状态?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t         <td>适合做空单或有多单早点卖出</td>\r\n");
      out.write("\t         <td>这 是超买之后所形成的卖压涌现，获利了结盘大量抛出之故 ，将下跌。</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <td>孕育线1</td>\r\n");
      out.write("\t         <td>阳线缩在较长的阳线之内。连续数天扬升之后，隔天出现一根小阳线，并完全孕育在前日之大阳线之中</td>\r\n");
      out.write("\t         <td>是否这种状态?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t         <td>适合做空单或有多单早点卖出</td>\r\n");
      out.write("\t         <td>表示上升乏力，是暴跌的前兆</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <td>孕育线2</td>\r\n");
      out.write("\t         <td>阴线缩在较长的阳线之内。经过连日飙升后，当日的开收盘价完全孕育在前一日的大 阳线之中，并出现一根阴线</td>\r\n");
      out.write("\t         <td>是否这种状态?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t         <td>适合做空单或有多单早点卖出</td>\r\n");
      out.write("\t         <td>这也代表上涨力道不足，是 下跌的前兆。若隔天再拉出一条上影阴线，更可判断为行 情暴跌的征兆</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <td>上吊阳线</td>\r\n");
      out.write("\t         <td><b>于高档开盘</b>，先前的买盘因获利了结而杀出，使得大势随之滑落，低档又逢有力承接，价格再度攀升，<b>形成了下影 线为实线的三倍以上</b>。</td>\r\n");
      out.write("\t         <td>是否这种状态?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t         <td>空手者不宜冒然介入，持仓者宜逢高 抛售</td>\r\n");
      out.write("\t         <td>此图形看起来似乎买盘转强，然宜慎防主力拉高出货，空手者不宜冒然介入，持仓者宜逢高 抛售</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t         <td>跳空</td>\r\n");
      out.write("\t         <td>所谓跳空即两条阴阳线之间不互相接触，中间有空格的意思</td>\r\n");
      out.write("\t         <td>是否这种状态?</td>\r\n");
      out.write("\t         <td><select><option value=\"-1\">请回答</option><option value=\"0\">否</option><option value=\"1\">是一个跳空</option><option value=\"2\">是两个个跳空</option><option value=\"3\">是三个跳空</option><option value=\"4\">是更多跳空</option></select></td>\r\n");
      out.write("\t         <td>在第二根跳空阳线出现后，即应先行获利了结，以防回档 惨遭套牢，适宜观望，不宜做单</td>\r\n");
      out.write("\t         <td>连续出现三根跳空阳线后，卖压必现，一般投资人在第二根跳空阳线出现后，即应先行获利了结，以防回档 惨遭套牢。</td>\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t   </tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
