/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-05-01 06:49:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./easyui-html5.jsp", Long.valueOf(1430462985455L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write(' ');

 String name = "管理员";
 
      out.write("\n");
      out.write(" <!DOCTYPE html>\n");
      out.write("<html lang=\"zh\">\n");
      out.write("<head>");
      out.write("\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" content=\"ie=edge\"/>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>系统首页</title>\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/icon/icon.css?3\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/easyui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./resources/easyui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.mask {  \r\n");
      out.write("            position: absolute; top: 0px; filter: alpha(opacity=60); background-color: #777;\r\n");
      out.write("            z-index: 1002; left: 0px;\r\n");
      out.write("            opacity:0.5; -moz-opacity:0.5;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t function getPageArea() {\r\n");
      out.write("\t\tif (document.compatMode == 'BackCompat') {\r\n");
      out.write("\t\t\treturn {\r\n");
      out.write("\t\t\t\twidth: Math.max(document.body.scrollWidth, document.body.clientWidth),\r\n");
      out.write("\t\t\t\theight: Math.max(document.body.scrollHeight, document.body.clientHeight)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\treturn {\r\n");
      out.write("\t\t\t\twidth: Math.max(document.documentElement.scrollWidth, document.documentElement.clientWidth),\r\n");
      out.write("\t\t\t\theight: Math.max(document.documentElement.scrollHeight, document.documentElement.clientHeight)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery.extend({ \r\n");
      out.write("\t\tshowMask: function(el, msg) {\r\n");
      out.write("\t\t\tif(!el)el =document.body;\r\n");
      out.write("\t\t\tvar _1c3=$(el);\r\n");
      out.write("\t\t\tmsg = msg?msg:\"\";\r\n");
      out.write("\t\t\tif(!_1c3.children(\"div.datagrid-mask\").length){\r\n");
      out.write("\t\t\t\t$(\"<div class=\\\"datagrid-mask\\\" style=\\\"display:block\\\"></div>\").appendTo(_1c3);\r\n");
      out.write("\t\t\t\tvar msg=$(\"<div class=\\\"datagrid-mask-msg\\\" style=\\\"display:block;left:50%\\\"></div>\").html(msg).appendTo(_1c3);\r\n");
      out.write("\t\t\t\tmsg.css(\"marginLeft\",-msg.outerWidth()/2);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, \r\n");
      out.write("\t\thideMask: function(el){ \r\n");
      out.write("\t\t\tif(!el)el =document.body;\r\n");
      out.write("\t\t   var _1c4=$(el);\r\n");
      out.write("\t\t   \tvar mask = _1c4.children(\"div.datagrid-mask-msg\");\r\n");
      out.write("\t\t   \tif(mask){\r\n");
      out.write("\t\t   \t\t_1c4.children(\"div.datagrid-mask-msg\").remove();\r\n");
      out.write("\t\t\t\t_1c4.children(\"div.datagrid-mask\").remove();\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tDate.prototype.format = function(format){ \r\n");
      out.write("\t\tvar o = { \r\n");
      out.write("\t\t\t\"M+\" : this.getMonth()+1, //month \r\n");
      out.write("\t\t\t\"d+\" : this.getDate(), //day \r\n");
      out.write("\t\t\t\"h+\" : this.getHours(), //hour \r\n");
      out.write("\t\t\t\"m+\" : this.getMinutes(), //minute \r\n");
      out.write("\t\t\t\"s+\" : this.getSeconds(), //second \r\n");
      out.write("\t\t\t\"q+\" : Math.floor((this.getMonth()+3)/3), //quarter \r\n");
      out.write("\t\t\t\"S\" : this.getMilliseconds() //millisecond \r\n");
      out.write("\t\t} \r\n");
      out.write("\r\n");
      out.write("\t\tif(/(y+)/.test(format)) { \r\n");
      out.write("\t\t\tformat = format.replace(RegExp.$1, (this.getFullYear()+\"\").substr(4 - RegExp.$1.length)); \r\n");
      out.write("\t\t} \r\n");
      out.write("\r\n");
      out.write("\t\tfor(var k in o) { \r\n");
      out.write("\t\t\tif(new RegExp(\"(\"+ k +\")\").test(format)) { \r\n");
      out.write("\t\t\t\tformat = format.replace(RegExp.$1, RegExp.$1.length==1 ? o[k] : (\"00\"+ o[k]).substr((\"\"+ o[k]).length)); \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\treturn format; \r\n");
      out.write("\t} \r\n");
      out.write("\t//使用方法 \r\n");
      out.write("\t//var now = new Date(); \r\n");
      out.write("\t//var nowStr = now.format(\"yyyy-MM-dd hh:mm:ss\"); \r\n");
      out.write("\t//使用方法2: \r\n");
      out.write("\t//var testDate = new Date(); \r\n");
      out.write("\t//var testStr = testDate.format(\"YYYY年MM月dd日hh小时mm分ss秒\"); \r\n");
      out.write("</script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var opTabIndex = -1;\n");
      out.write("function menuHandler(item){\n");
      out.write("\t\t\tif(\"close\" == item.name){\n");
      out.write("\t\t\t\t$('#tt').tabs('close',opTabIndex);\n");
      out.write("\t\t\t}else if(\"close all\" == item.name){\n");
      out.write("\t\t\t\tvar tabs = $('#tt').tabs('tabs');\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tfor(var i=tabs.length-1;i>=0;i--){\n");
      out.write("\t\t\t\t\t$('#tt').tabs('close',i);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}else if(\"close other\" == item.name){\n");
      out.write("\t\t\t\tvar tabs = $('#tt').tabs('tabs');\n");
      out.write("\t\t\t\tfor(var i=tabs.length-1;i>=0;i--){\n");
      out.write("\t\t\t\t\tif(i == opTabIndex) continue;\n");
      out.write("\t\t\t\t\t$('#tt').tabs('close',i);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("}\n");
      out.write("function onContextMenuFn(e, title,index){\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\topTabIndex = -1;\n");
      out.write("\t\t\t\t\te.preventDefault();\n");
      out.write("\t\t\t\t\tvar tabs = $('#tt').tabs('tabs');\n");
      out.write("\t\t\t\t \t$(\"#ci\").show();\n");
      out.write("\t\t\t\t \t$(\"#ca\").show();\n");
      out.write("\t\t\t\t \t$(\"#co\").show();\n");
      out.write("\t\t\t\t\tif(index == 0  ){\n");
      out.write("\t\t\t\t\t\tif(tabs.length == 1){\n");
      out.write("\t\t\t\t\t\t\t$(\"#co\").hide();\n");
      out.write("\t\t\t\t\t\t\t$(\"#ca\").hide();\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\topTabIndex = index;\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$('#mm').menu('show', {\n");
      out.write("\t\t\t\t\t\tleft: e.pageX,\n");
      out.write("\t\t\t\t\t\ttop: e.pageY\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<body class=\"easyui-layout\">\n");
      out.write("\t<div data-options=\"region:'north',border:false\" style=\"PADDING-BOTTOM: 5px; PADDING-LEFT: 5px; PADDING-RIGHT: 5px; HEIGHT: auto; PADDING-TOP: 5px\"   class=datagrid-toolbar>\n");
      out.write("\t\t<table width=\"100%\">\n");
      out.write("\t\t\t<tr width=\"100%\">\n");
      out.write("\t\t\t\t<td width=\"50%\">\n");
      out.write("\t\t\t\t\t 欢迎您:");
      out.print(name );
      out.write("&nbsp;&nbsp;\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t\t<td align=\"right\" width=\"50%\">\n");
      out.write("\t\t\t\t<!-- \n");
      out.write("\t\t\t\t\t <a href=\"#\" class=\"easyui-linkbutton\" onclick=\"addTabPanel('userhome')\" data-options=\"plain:true,iconCls:'user_btn'\">个人中心</a>\n");
      out.write("\t\t\t\t\t <a href=\"#\" class=\"easyui-linkbutton\" onclick=\"logout()\" data-options=\"plain:true,iconCls:'poweroff_btn'\">退出</a>\n");
      out.write("\t\t\t\t -->\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t<div data-options=\"region:'west',split:true,border:true,title:'&nbsp;'\"\" style=\"width:250px;padding:10px;\">\n");
      out.write("\t\t<ul class=\"easyui-tree\" data-options=\"\n");
      out.write("\t\turl:'");
      out.print(request.getContextPath() );
      out.write("/resources/menudata.json?'+new Date().getTime(),\n");
      out.write("\t\tmethod:'get',\n");
      out.write("\t\tloadFilter:function(data){ return treeloadFilter(data);},\n");
      out.write("\t\tanimate:true,\n");
      out.write("\t\tonClick:treeClickFn\n");
      out.write("\t\t\"></ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div region=\"center\" border=\"false\">\n");
      out.write("\t\t\t<div id=\"tt\" class=\"easyui-tabs\" fit=\"true\" border=\"false\" plain=\"true\" \n");
      out.write("\t\t\t\tdata-options=\"onContextMenu:onContextMenuFn\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"mm\" class=\"easyui-menu\" data-options=\"onClick:menuHandler\" style=\"width:120px;\">\n");
      out.write("\t\t<div data-options=\"name:'close'\" id=\"ci\">关闭</div>\n");
      out.write("\t\t<div data-options=\"name:'close all'\" id=\"ca\">全部关闭</div>\n");
      out.write("\t\t<div data-options=\"name:'close other'\"  id=\"co\">关闭其他</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function treeloadFilter(menus ,usecheck){\n");
      out.write("\tif(menus.length==0)return menus;\n");
      out.write(" \t var mapdata = {};\n");
      out.write("\t  //第一次组织树节点内容\n");
      out.write("\t  for(var i=0;i<menus.length;i++)\n");
      out.write("\t  {\n");
      out.write("\t      var node = menus[i];\n");
      out.write("\t      var menuname = node['name'];\n");
      out.write("\t      var parentNo = node['pid'];\n");
      out.write("\t      var aid = node['id'] ;\n");
      out.write("\t      \n");
      out.write("\t      var path = node['path'];\n");
      out.write("\t      var isbutton = node['isbutton'];\n");
      out.write("\t      var authorityCode = node[\"btnflag\"];\n");
      out.write("\t      \n");
      out.write("\t\t  if(isbutton == 1){\n");
      out.write("\t\t\t\tcontinue;\n");
      out.write("\t\t  }\n");
      out.write("\t      mapdata[\"id_\"+aid]= {\n");
      out.write("\t    \t\t  id:aid,\n");
      out.write("\t    \t\t  text:menuname,\n");
      out.write("\t    \t\t  parentNo:parentNo,\n");
      out.write("\t    \t\t  state:'closed',\n");
      out.write("\t    \t\t  attributes:{\n");
      out.write("\t    \t\t  \turl:path,\n");
      out.write("\t    \t\t  \tisbutton:isbutton,\n");
      out.write("\t    \t\t  \tauthorityCode:authorityCode,\n");
      out.write("\t    \t\t  \tparentId:parentNo\n");
      out.write("\t    \t\t  }\n");
      out.write("\t    };\n");
      out.write("\t    \n");
      out.write("\t     if(usecheck)\n");
      out.write("\t\t {\n");
      out.write("\t\t \tmapdata[\"id_\"+aid]['checked']=false;\n");
      out.write("\t\t }\n");
      out.write("\n");
      out.write("\t  }\n");
      out.write("  var ret = [];\n");
      out.write("  for(var key in mapdata)\n");
      out.write("  {\n");
      out.write("      var node = mapdata[key];\n");
      out.write("      var pid = mapdata[key]['parentNo'];\n");
      out.write("      if(mapdata[\"id_\"+pid])\n");
      out.write("      {\n");
      out.write("          if(typeof mapdata[\"id_\"+pid]['children'] == 'undefined')\n");
      out.write("          {\n");
      out.write("              mapdata[\"id_\"+pid]['children'] = [];\n");
      out.write("          }\n");
      out.write("          mapdata[\"id_\"+pid]['children'].push(mapdata[key]);\n");
      out.write("      }else\n");
      out.write("      {\n");
      out.write("          ret.push(mapdata[key]);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("  }\n");
      out.write("   for(var key in mapdata)\n");
      out.write("  {\n");
      out.write("       var node = mapdata[key];\n");
      out.write("       if(node['children'] == null){\n");
      out.write("       \t\tnode['state'] = 'open';\n");
      out.write("       }\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\t\n");
      out.write("\tif(ret.length>0){ret[0]['state'] = 'open';} \n");
      out.write("  return ret;\n");
      out.write("}\n");
      out.write("function treeClickFn(node){ \n");
      out.write("\t\tvar attributs = node.attributes;\n");
      out.write("\t \tvar type = jQuery.type(attributs);\n");
      out.write("\t \tif(type == 'undefined'){return;}\n");
      out.write("\t \tvar url = attributs.url;\n");
      out.write("\t \tif($.trim(url).length == 0)return;\n");
      out.write("\t \tvar title = node.text;\n");
      out.write("\t \tif ($('#tt').tabs('exists',title)){\n");
      out.write("\t\t\t\t\t$('#tt').tabs('select', title);\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('#tt').tabs('add',{\n");
      out.write("\t\t\t\t\ttitle:title,\n");
      out.write("\t\t\t\t\tclosable:true,\n");
      out.write("\t\t\t\t\tcache:false,\n");
      out.write("\t\t\t\t\tcontent:'<iframe scrolling=\"yes\" frameborder=\"0\"  src=\"");
      out.print(request.getContextPath() );
      out.write("'+url+'?d='+new  Date().getMilliseconds()+'\" style=\"width:100%;height:100%;\"></iframe>'\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("}\n");
      out.write("function addTabPanel(flag){\n");
      out.write("\t var node = {};\n");
      out.write("\t if(flag == 'userhome'){\n");
      out.write("\t \tnode = {\n");
      out.write("\t \t\ttext:\"个人中心\",\n");
      out.write("\t \t\tattributes:{\n");
      out.write("\t \t\t\turl:\"/admin/userhome/index\"\n");
      out.write("\t \t\t}\n");
      out.write("\t \t}\n");
      out.write("\t }\n");
      out.write("\t treeClickFn(node);\n");
      out.write("}\n");
      out.write("function logout(){\n");
      out.write("\t$.messager.confirm('系统提示', '您确定要退出该系统吗?', function(r){\n");
      out.write("\t\tif (r){\n");
      out.write("\t\t\twindow.location = \"/admin/logout\";\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
